# Download base image
FROM alpine:3.4 

MAINTAINER Quinn D Granfor, spootdev@gmail.com

LABEL www.mediakraken.org.version="dev-0.2.0"
LABEL Description="This image downloads and maintains all metadata"

# copy PIP requirements
ADD requirements.txt /mediakraken
WORKDIR /mediakraken

# Update repository and install packages
RUN apk add --update \
  postgresql-client \
  gcc \
  linux-headers \
  musl-dev \
  postgresql-dev \
  python-dev \
  py-pip \
  && pip install pytest-runner \
  && pip install -r requirements.txt \
  && pip uninstall -y pytest_runner \
  && apk del gcc linux-headers musl-dev postgresql-dev python-dev py-pip
  && rm requirements.txt

ADD wait-for-it.sh /mediakraken
# Copy the source files for the app
ADD src /mediakraken

CMD ["python", "main_server_trigger.py"]
