version: '3'

services:
  nginx-rtmp-vod-ffmpeg:
      build:
        context: .

      volumes:
        - ./nginx.conf.webcam:/etc/nginx/nginx.conf
        - ./docker-entrypoint.sh:/docker-entrypoint.sh

      ports:
        - "1935:1935"
        - "8080:8080"

      devices:
        - "/dev/video0:/dev/video0"
