# -*- coding: utf-8 -*-
"""The user module."""
from . import views
from . import views_3d
from . import views_cctv
from . import views_chromecast
from . import views_class
from . import views_comic_reader
from . import views_games
from . import views_hardware
from . import views_hardware_hue
from . import views_home_media
from . import views_images
from . import views_internet
from . import views_media_new
from . import views_metadata_album
from . import views_metadata_game
from . import views_metadata_game_system
from . import views_metadata_movie
from . import views_metadata_music_video
from . import views_metadata_people
from . import views_metadata_periodical
from . import views_metadata_sports
from . import views_metadata_tv
from . import views_movie
from . import views_movie_collection
from . import views_movie_genre
from . import views_music
from . import views_music_video
from . import views_periodicals
from . import views_playback
from . import views_queue
from . import views_search
from . import views_sports
from . import views_sync
from . import views_tv
from . import views_tv_live
