apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: appserver
  name: appserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: appserver
    spec:
      containers:
      - command:
        - ./wait-for-it-ash.sh
        - -h
        - mkstack_pgbouncer
        - -p
        - "6432"
        - -t
        - "120"
        - --
        - python3
        - main_server.py
        env:
        - name: POSTGRES_PASSWORD
          value: /run/secrets/db_password
        - name: SECURE
          value: /run/secrets/secure_key
        - name: SWARMIP
        image: th-registry-1.beaverbay.local:5000/mediakraken/mkserver:dev
        name: appserver
        resources: {}
        volumeMounts:
        - mountPath: /mediakraken/key
          name: mediakraken-vol-certs
        - mountPath: /var/run/docker.sock
          name: appserver-claim1
          readOnly: true
        - mountPath: /mediakraken/devices
          name: mediakraken-vol-devices
        - mountPath: /mediakraken/secure
          name: appserver-claim3
      restartPolicy: Always
      volumes:
      - name: mediakraken-vol-certs
        persistentVolumeClaim:
          claimName: mediakraken-vol-certs
      - name: appserver-claim1
        persistentVolumeClaim:
          claimName: appserver-claim1
          readOnly: true
      - name: mediakraken-vol-devices
        persistentVolumeClaim:
          claimName: mediakraken-vol-devices
      - name: appserver-claim3
        persistentVolumeClaim:
          claimName: appserver-claim3
status: {}
