apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: broadcast
  name: broadcast
spec:
  ports:
  - name: "9101"
    port: 9101
    targetPort: 9101
  selector:
    io.kompose.service: broadcast
status:
  loadBalancer: {}
