apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: broadcast
  name: broadcast
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: broadcast
    spec:
      containers:
      - command:
        - python3
        - subprogram_broadcast.py
        env:
        - name: HOST_IP
        - name: SWARMIP
        image: th-registry-1.beaverbay.local:5000/mediakraken/mkbroadcast:dev
        name: broadcast
        ports:
        - containerPort: 9101
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: broadcast-claim0
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: broadcast-claim0
        persistentVolumeClaim:
          claimName: broadcast-claim0
          readOnly: true
status: {}
