apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: MAX_CONNECTIONS
          value: "100"
        - name: MAX_WAL_SENDERS
          value: "10"
        - name: POSTGRES_PASSWORD
          value: /run/secrets/db_password
        - name: SHARED_BUFFERS
          value: 4096MB
        - name: WORK_MEM
          value: 256MB
        - name: log_min_duration_statement
          value: "1000"
        image: th-registry-1.beaverbay.local:5000/mediakraken/mkdatabase:dev
        name: database
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: mediakraken-vol-postgresql
      restartPolicy: Always
      volumes:
      - name: mediakraken-vol-postgresql
        persistentVolumeClaim:
          claimName: mediakraken-vol-postgresql
status: {}
