apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: download
  name: download
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: download
    spec:
      containers:
      - command:
        - ./wait-for-it-ash.sh
        - -h
        - mkstack_pgbouncer
        - -p
        - "6432"
        - -t
        - "120"
        - --
        - python3
        - main_download.py
        env:
        - name: POSTGRES_PASSWORD
          value: /run/secrets/db_password
        image: th-registry-1.beaverbay.local:5000/mediakraken/mkdownload:dev
        name: download
        resources: {}
      restartPolicy: Always
status: {}
