apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: moosefsmaster
  name: moosefsmaster
spec:
  ports:
  - name: "9425"
    port: 9425
    targetPort: 9425
  selector:
    io.kompose.service: moosefsmaster
status:
  loadBalancer: {}
