apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: moosefsmaster
  name: moosefsmaster
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: moosefsmaster
    spec:
      containers:
      - image: th-registry-1.beaverbay.local:5000/mediakraken/mkmoosemaster:dev
        name: moosefsmaster
        ports:
        - containerPort: 9425
        resources: {}
      restartPolicy: Always
status: {}
