apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
  - name: "8900"
    port: 8900
    targetPort: 8900
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
