apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  ports:
  - name: "5050"
    port: 5050
    targetPort: 5050
  selector:
    io.kompose.service: pgadmin
status:
  loadBalancer: {}
