apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pgadmin
    spec:
      containers:
      - env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: spootdev@gmail.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: metaman
        image: th-registry-1.beaverbay.local:5000/mediakraken/mkpgadmin:dev
        name: pgadmin
        ports:
        - containerPort: 5050
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: mediakraken-vol-pgadmin
      restartPolicy: Always
      volumes:
      - name: mediakraken-vol-pgadmin
        persistentVolumeClaim:
          claimName: mediakraken-vol-pgadmin
status: {}
