apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: pgbouncerhero
  name: pgbouncerhero
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pgbouncerhero
    spec:
      containers:
      - env:
        - name: PGBOUNCERHERO_DATABASE_URL
          value: postgres://postgres:owfohiwehCHANGEMEjiow2rJ@mkstack_pgbouncer:6432/postgres
        image: th-registry-1.beaverbay.local:5000/mediakraken/mkpgbouncerhero:dev
        name: pgbouncerhero
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
