apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: pika
  name: pika
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pika
    spec:
      containers:
      - command:
        - python3
        - subprogram_pika.py
        env:
        - name: POSTGRES_PASSWORD
          value: /run/secrets/db_password
        image: th-registry-1.beaverbay.local:5000/mediakraken/mkpika:dev
        name: pika
        resources: {}
      restartPolicy: Always
status: {}
