apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: portainer
  name: portainer
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: portainer
status:
  loadBalancer: {}
