apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: portainer
  name: portainer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: portainer
    spec:
      containers:
      - args:
        - -H
        - tcp://tasks.portaineragent:9001
        - --tlsskipverify
        image: portainer/portainer
        name: portainer
        ports:
        - containerPort: 9000
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: portainer-data
      restartPolicy: Always
      volumes:
      - name: portainer-data
        persistentVolumeClaim:
          claimName: portainer-data
status: {}
