apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: rokuthumb
  name: rokuthumb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rokuthumb
    spec:
      containers:
      - command:
        - python3
        - subprogram_roku_thumbnail_generate.py
        image: th-registry-1.beaverbay.local:5000/mediakraken/mkrokuthumb:dev
        name: rokuthumb
        resources: {}
      restartPolicy: Always
status: {}
