apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: transmission
  name: transmission
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: transmission
    spec:
      containers:
      - env:
        - name: PASSWORD
          value: metaman
        - name: USERNAME
          value: metaman
        image: th-registry-1.beaverbay.local:5000/mediakraken/mktransmission:dev
        name: transmission
        ports:
        - containerPort: 9091
        - containerPort: 51413
        - containerPort: 51413
          protocol: UDP
        resources: {}
        volumeMounts:
        - mountPath: /transmission/downloads
          name: mediakraken-vol-transmission
        - mountPath: /transmission/incomplete
          name: mediakraken-vol-transmission-incomplete
      restartPolicy: Always
      volumes:
      - name: mediakraken-vol-transmission
        persistentVolumeClaim:
          claimName: mediakraken-vol-transmission
      - name: mediakraken-vol-transmission-incomplete
        persistentVolumeClaim:
          claimName: mediakraken-vol-transmission-incomplete
status: {}
