[package]
name = "mk_lib_logging"
version = "0.0.1"
edition = "2018"

[profile.release]
panic = 'abort'

[dependencies]
chrono = "0.4"
reqwest = { version = "0.11.3", default-features = false, features = ["json", "rustls-tls"] }
serde_json = "1.0.64"

[dev-dependencies]
tokio-test = "*"