# Download base image
FROM mediakraken/mkbase37py3

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image holds the hardware app"

# copy PIP requirements
ADD requirements.txt /mediakraken
WORKDIR /mediakraken

RUN apk add --update \
  gcc \
  linux-headers \
  libffi-dev \
  musl-dev \
  python3-dev \
  && pip3 install -r requirements.txt \
  && rm requirements.txt \
  && apk del \
  gcc \
  linux-headers \
  musl-dev \
  python3-dev \
  && rm -rf /var/cache/apk/*

ADD wait-for-it-ash.sh /mediakraken
# Copy the source files for the app
ADD src /mediakraken

CMD ["/bin/ash"]
