version: '3'

services:
  postgres:
    container_name: postgres
    restart: always #Autostart
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - DEBUG=false
      - POSTGRES_PASSWORD=postgres

  pgadmin4:
    container_name: pgadmin4
    restart: always #Autostart
    image: chorss/docker-pgadmin4
    volumes:
      - /CHANGE_DIRECTORY:/data
    links:
      - postgres
    ports:
      - 5050:5050