# Download base image
FROM alpine:3.6

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image holds the downloader app"

# create work dir
RUN mkdir /mediakraken
RUN mkdir /mediakraken/downloads

# copy PIP requirements
ADD requirements.txt /mediakraken
WORKDIR /mediakraken

RUN apk add --update \
  py-pip \
  && pip install --upgrade pip \
  && pip install -r requirements.txt \
  && apk del \
  py-pip \
  && rm -rf /var/cache/apk/* \
  && rm requirements.txt

ADD wait-for-it-ash.sh /mediakraken
ADD archive.txt /mediakraken
# Copy the source files for the app
ADD src /mediakraken

CMD ["/bin/ash"]
