version: '2'
services:
  mkserver:
    image: mediakraken/mkserver
    ports:
     - "8080:8080"
    volumes:
     - .:/code
    depends_on:
     - mkdatabase
  mkdatabase:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=metamandb
      - POSTGRES_PASSWORD=metamanpg
