version: '2'
services:
  mkserver:
    container_name: mkhost
    image: mediakraken/mkserver:dev-0.1.12
    ports:
     - "5000:8080"
    volumes:
     - .:/code
    restart: unless-stopped
    depends_on:
     - postgres
    env_file: ./mediakraken.env
    command: ["python", "main_server.py"]
  postgres:
    image: postgres:9.5.4
    env_file: ./mediakraken.env
