docker push mediakraken/mkbase34:latest
docker push mediakraken/mkbase34py3:latest
docker push mediakraken/mkbase35:latest
docker push mediakraken/mkbase35py3:latest
docker push mediakraken/mkbase36:latest
docker push mediakraken/mkbase36py3:latest
docker push mediakraken/mkbase37:latest
docker push mediakraken/mkbase37py3:latest
docker push mediakraken/mkbaseffmpeg:latest
docker push mediakraken/mkbaseffmpegnvidia:latest
docker push mediakraken/mkbaseffmpegnvidiadebian:latest
docker push mediakraken/mkbasenvidiadebain:latest
docker push mediakraken/mkbroadcast:latest
docker push mediakraken/mkdatabase:latest
docker push mediakraken/mkdebug:latest
docker push mediakraken/mkdevicescan:latest
docker push mediakraken/mkdocker:latest
docker push mediakraken/mkdownload:latest
docker push mediakraken/mkelk:latest
docker push mediakraken/mkmetadata:latest
docker push mediakraken/mkmumble:latest
docker push mediakraken/mkmusicbrainz:latest
docker push mediakraken/mknginx:latest
docker push mediakraken/mknginxrtmp:latest
docker push mediakraken/mkopenldap:latest
#docker push mediakraken/mkpgadmin:latest
docker push mediakraken/mkpgbounce:latest
docker push mediakraken/mkprefetchtmdb:latest
docker push mediakraken/mkrabbitmq:latest
docker push mediakraken/mkredis:latest
#docker push mediakraken/mkripper:latest
docker push mediakraken/mkserver:latest
docker push mediakraken/mkslave:latest
docker push mediakraken/mkslavenvidia:latest
docker push mediakraken/mkslavenvidiadebian:latest
docker push mediakraken/mksmtp:latest
docker push mediakraken/mkteamspeak:latest
docker push mediakraken/mktransmission:latest
docker push mediakraken/mkwebapp:latest
docker push mediakraken/mkwireshark:latest
