docker tag mk_appserver:latest mediakraken/mkserver:latest
#docker tag mk_basenodeffmpeg:latest mediakraken/mkbasenodeffmpeg:latest
docker tag mk_broadcast:latest mediakraken/mkbroadcast:latest
docker tag mk_cloud:latest mediakraken/mkcloud:latest
docker tag mk_database:latest mediakraken/mkdatabase:latest
docker tag mk_download mediakraken/mkdownload:latest
#docker tag mk_devicescan:latest mediakraken/mkdevicescan:latest
#docker tag mk_elk:latest mediakraken/mkelk:latest
docker tag mk_ffprobe mediakraken/mkffprobe:latest
docker tag mk_hardware mediakraken/mkhardware:latest
docker tag mk_metadata:latest mediakraken/mkmetadata:latest
#docker tag mk_mumble mediakraken/mkmumble:latest
docker tag mk_nginx:latest mediakraken/mknginx:latest
#docker tag mk_pgadmin mediakraken/mkpgadmin:latest
docker tag mk_pgbounce:latest mediakraken/mkpgbounce:latest
#docker tag mk_prefetchtmdb:latest mediakraken/mkprefetchtmdb:latest
#docker tag mk_prefetchtmdb:latest mediakraken/mkprefetchtvmaze:latest
docker tag mk_rabbit:latest mediakraken/mkrabbitmq:latest
docker tag mk_redis:latest mediakraken/mkredis:latest
#docker tag mk_ripper mediakraken/mkripper:latest
docker tag mk_smtp mediakraken/mksmtp:latest
#docker tag mk_transmission:latest mediakraken/mktransmission:latest
docker tag mk_webserver:latest mediakraken/mkwebapp:latest
