docker tag alpine_appserver:latest mediakraken/mkserver:latest
docker tag alpine_broadcast:latest mediakraken/mkbroadcast:latest
docker tag alpine_cron:latest mediakraken/mkcron:latest
docker tag alpine_database:latest mediakraken/mkdatabase:latest
docker tag alpine_download:latest mediakraken/mkdownload:latest
docker tag alpine_ffprobe mediakraken/mkffprobe:latest
docker tag alpine_hardware mediakraken/mkhardware:latest
docker tag alpine_metadata:latest mediakraken/mkmetadata:latest
docker tag alpine_nginx:latest mediakraken/mknginx:latest
docker tag alpine_pika:latest mediakraken/mkpika:latest
docker tag alpine_pgbounce:latest mediakraken/mkpgbounce:latest
docker tag alpine_rabbit:latest mediakraken/mkrabbitmq:latest
docker tag alpine_reactor:latest mediakraken/mkreactor:latest
docker tag alpine_redis:latest mediakraken/mkredis:latest
docker tag alpine_rokuthumb mediakraken/mkrokuthumb:latest
docker tag alpine_webserver:latest mediakraken/mkwebapp:latest
