docker tag alpine_appserver:latest mediakraken/mkserver:dev
docker tag alpine_broadcast:latest mediakraken/mkbroadcast:dev
docker tag alpine_cron:latest mediakraken/mkcron:dev
docker tag alpine_database:latest mediakraken/mkdatabase:dev
docker tag alpine_download:latest mediakraken/mkdownload:dev
docker tag alpine_ffprobe mediakraken/mkffprobe:dev
docker tag alpine_hardware mediakraken/mkhardware:dev
docker tag alpine_metadata:latest mediakraken/mkmetadata:dev
docker tag alpine_nginx:latest mediakraken/mknginx:dev
docker tag alpine_pika:latest mediakraken/mkpika:dev
docker tag alpine_pgbounce:latest mediakraken/mkpgbounce:dev
docker tag alpine_rabbit:latest mediakraken/mkrabbitmq:dev
docker tag alpine_reactor:latest mediakraken/mkreactor:dev
docker tag alpine_redis:latest mediakraken/mkredis:dev
docker tag alpine_rokuthumb mediakraken/mkrokuthumb:dev
docker tag alpine_webserver:latest mediakraken/mkwebapp:dev
