# Download base image
FROM alpine:3.4 

MAINTAINER Quinn D Granfor, spootdev@gmail.com

LABEL www.mediakraken.org.version="dev-0.2.0"
LABEL Description="This image scans for new hardware devices"

RUN mkdir /mediakraken
WORKDIR /mediakraken

# Update repository and install packages
RUN apk add --update \
  python \
  alpine-sdk

# Copy the source files for the app
ADD src /mediakraken

RUN tar -xvf libhdhomerun* \
  && cd libhdhomerun \
  && make \
  && make install \
  && apk del alpine-sdk

CMD ["/bin/ash"]



