machine:
  services:
    - docker

dependencies:
  override:
    - RELEASE=$(grep "TS3_VERSION=" Dockerfile | sed 's|^.*=||g' |awk '{print $1}'); docker build -t polinux/teamspeak:$RELEASE .
    - docker build -t polinux/teamspeak:latest .

test:
  override:
    - RELEASE=$(grep "TS3_VERSION=" Dockerfile | sed 's|^.*=||g' |awk '{print $1}'); docker run -d -p 9987:9987/udp -p 10011:10011 -p 30033:30033 --name ts3 polinux/teamspeak:$RELEASE
    - while true; do if docker logs ts3 | grep "listening on 0.0.0.0"; then break; else sleep 1; fi done

deployment:
  production:
    branch: master
    commands:
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - RELEASE=$(grep "TS3_VERSION=" Dockerfile | sed 's|^.*=||g' |awk '{print $1}'); docker push polinux/teamspeak:$RELEASE
      - docker push polinux/teamspeak:latest
