[package]
name = "mk_lib_metadata"
version = "0.0.1"
edition = "2018"

[profile.release]
panic = 'abort'

[dependencies]
reqwest = { version = "0.11.3", default-features = false, features = ["json", "rustls-tls"] }

[dev-dependencies]
tokio-test = "*"