# Download base image
FROM alpine:3.5

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image holds the image for the phppgadmin"

RUN apk add --update \
  lighttpd \
  php5-fpm \
  php5-common \
  php5-iconv \ 
  php5-json \
  php5-gd \
  php5-curl \
  php5-xml \
  php5-pgsql \
  php5-imap \
  php5-cgi \
  fcgi \
  php5-pdo \
  php5-pdo_pgsql \
  php5-soap \
  php5-xmlrpc \
  php5-posix \
  php5-mcrypt \
  php5-gettext \
  php5-ldap \
  php5-ctype \
  php5-dom \
  postgresql \
  postgresql-client \
  && rm -rf /var/cache/apk/* \
  && adduser www-data -G www-data -H -s /bin/false -D \
  && mkdir /run/lighttpd \
  && chmod 777 /run/lighttpd

ADD lighttpd.conf /etc/lighttpd/lighttpd.conf

ADD index.php /var/www/localhost/htdocs

ADD phppgadmin-master.tar.bz2 /var/www/localhost/htdocs/

RUN mv /var/www/localhost/htdocs/phppgadmin-master /var/www/localhost/htdocs/phppgadmin

ADD config.inc.php /var/www/localhost/htdocs/phppgadmin/conf/config.inc.php

EXPOSE 80

CMD ["/bin/ash"]

