# Download base image
FROM alpine:3.4

MAINTAINER Quinn D Granfor, spootdev@gmail.com

LABEL www.mediakraken.org.version="dev-0.2.0"
LABEL Description="This image holds the image for the phppgadmin"

RUN apk add --update \
  openrc \
  lighttpd php5-common php5-iconv php5-json php5-gd php5-curl php5-xml php5-pgsql php5-imap php5-cgi fcgi \
  php5-pdo php5-pdo_pgsql php5-soap php5-xmlrpc php5-posix php5-mcrypt php5-gettext php5-ldap php5-ctype php5-dom \
  postgresql-client

COPY etc/lighttpd/* /etc/lighttpd/

ADD phpPgAdmin-5.1.tar.bz2 /var/www/localhost/htdocs/phppgadmin

ADD config.inc.php /var/www/localhost/htdocs/phppgadmin/conf/config.inc.php

RUN chown -R lighttpd: /var/www/localhost/htdocs/

EXPOSE 80

CMD ["/bin/ash"]

