# Download base image
FROM alpine:3.6

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image holds the image for the phppgadmin"

RUN apk add --update \
  lighttpd \
  php7-fpm \
  php7-common \
  php7-iconv \ 
  php7-json \
  php7-gd \
  php7-curl \
  php7-xml \
  php7-pgsql \
  php7-imap \
  php7-cgi \
  fcgi \
  php7-pdo \
  php7-pdo_pgsql \
  php7-soap \
  php7-xmlrpc \
  php7-posix \
  php7-mcrypt \
  php7-gettext \
  php7-ldap \
  php7-ctype \
  php7-dom \
  postgresql \
  postgresql-client \
  && rm -rf /var/cache/apk/* \
  && adduser www-data -G www-data -H -s /bin/false -D \
  && mkdir /run/lighttpd \
  && chmod 777 /run/lighttpd

ADD lighttpd.conf /etc/lighttpd/lighttpd.conf

ADD index.php /var/www/localhost/htdocs

ADD phppgadmin-master.tar.bz2 /var/www/localhost/htdocs/

RUN mv /var/www/localhost/htdocs/phppgadmin-master /var/www/localhost/htdocs/phppgadmin

ADD config.inc.php /var/www/localhost/htdocs/phppgadmin/conf/config.inc.php

EXPOSE 80

CMD ["/bin/ash"]

