---

# jenkins variables
project_name: docker-musicbrainz
external_type: na
custom_version_command: git ls-remote --tags https://github.com/metabrainz/musicbrainz-server.git | grep -v '{}' | tail -n 1 | awk -F / '{print $3}'
release_type: stable
release_tag: latest
ls_branch: master
repo_vars:
  - BUILD_VERSION_ARG = 'MUSICBRAINZ_RELEASE'
  - LS_USER = 'linuxserver'
  - LS_REPO = 'docker-musicbrainz'
  - CONTAINER_NAME = 'musicbrainz'
  - DOCKERHUB_IMAGE = 'linuxserver/musicbrainz'
  - DEV_DOCKERHUB_IMAGE = 'lsiodev/musicbrainz'
  - PR_DOCKERHUB_IMAGE = 'lspipepr/musicbrainz'
  - DIST_IMAGE = 'alpine'
  - MULTIARCH='true'
  - CI='false'
