# Download base image
FROM alpine:3.6

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image holds the pypy builder"

ARG ALPMIRROR
ARG PIPMIRROR

RUN apk add --no-cache ca-certificates

# create work dir
RUN mkdir /mediakraken

# copy PIP requirements
ADD requirements.txt /mediakraken

RUN wget https://bitbucket.org/pypy/pypy/downloads/pypy2-v5.9.0-src.tar.bz2
RUN tar -xjv --strip-components=1 -f pypy2-v5.9.0-src.tar.bz2;

WORKDIR /mediakraken

RUN sed -i "s/dl-cdn.alpinelinux.org/${ALPMIRROR}/" /etc/apk/repositories \
  && apk add --update \
  py2-pip \
  alpine-sdk \
  linux-headers \
  pkgconf-dev \
  libffi-dev \
  zlib-dev \
  libbz2 \
  expat-dev \
  bzip2-dev \
  ncurses-dev \
  sqlite-dev \
  gdbm-dev \
  python-dev \
  libressl-dev \
  && pip install --trusted-host -i http://${PIPMIRROR} -r requirements.txt \
  && cd pypy/goal \
  && python ../../rpython/bin/rpython --opt=jit \
  && cd ../tool/release \
# pax fail  && PYTHONPATH=../.. ./pypy-c ../tool/build_cffi_imports.py \
# pax fail  && ./package.py --archive-name=pypy-mediakraken \
  && rm -rf /var/cache/apk/*

CMD ["/bin/ash"]
