version: '3'

services:
  minecraft:
    ports:
      - "25565:25565"
    volumes:
      - "mcbig:/data"
    environment:
      EULA: "TRUE"
      MAX_MEMORY: 32G
      MAX_BUILD_HEIGHT: 256
      VIEW_DISTANCE: 15
      LEVEL_TYPE: LARGEBIOMES
      MAX_PLAYERS: 100
      CONSOLE: "false"
    image: itzg/minecraft-server
    restart: always
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"

volumes:
  mcbig:
  rcon:
