# Download base image
FROM alpine:3.5

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image holds the theater app for testing"

RUN mkdir /mediakraken

# copy PIP requirements
ADD requirements.txt /mediakraken
WORKDIR /mediakraken

RUN apk add --update \
  xorg-server \
  xf86-video-vesa \
  xf86-video-modesetting \
  xf86-input-evdev \
  xf86-input-mouse \
  xf86-input-keyboard \
  udev \
  xfce4 \
  python \
  cifs-utils \
  nfs-utils \
  py-pip \
  alpine-sdk \
  cython \
  python-dev \
  libffi-dev \
  libressl-dev \
  gstreamer1-dev \
  sdl2-dev \
  && pip install -r requirements.txt \
  && apk del \
  py-pip \
  alpine-sdk \
  python-dev \
  && apk add \
  py-setuptools \
  && rm requirements.txt \
  && rm -rf /var/cache/apk/* \
  && rc-update add netmount \
  && rc-update add dbus \
  && rc-update add rpcbind \
  && rc-update add lxdm \
  && rc-update -q del mdev sysinit \
  && rc-update -q add udev sysinit \
  && rc-update -q add udev-postmount default

ADD wait-for-it-ash.sh /mediakraken
# Copy the source files for the app
ADD src /mediakraken

CMD ["/bin/ash"]
