# Download base image
FROM mediakraken/mkbase37py3

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image holds the main server app"

# copy PIP requirements
ADD requirements.txt /mediakraken
WORKDIR /mediakraken

RUN apk add --update \
  cifs-utils \
  curl-dev \
  nfs-utils \
  openssl \
  alpine-sdk \
  libffi-dev \
  openldap-dev \
  jpeg-dev \
  libxml2-dev \
  libxslt-dev \
  linux-headers \
  musl-dev \
  net-snmp \
  net-snmp-dev \
  openldap-dev \
  portaudio-dev \
  python3-dev \
  py3-psycopg2 \
  openrc \
  && export PYCURL_SSL_LIBRARY=openssl \
  && pip3 install pycurl \
  && pip3 install -r requirements.txt \
  && apk del \
  alpine-sdk \
  libxml2-dev \
  libxslt-dev \
  linux-headers \
  musl-dev \
  net-snmp-dev \
  python3-dev \
  && apk add \
  py-setuptools \
  && rm -rf /var/cache/apk/* \
  && rm requirements.txt \
  && rc-update add netmount \
  && rc-update add rpcbind

ADD wait-for-it-ash.sh /mediakraken
ADD np_inline-0.3 /mediakraken/np_inline
RUN cd /mediakraken/np_inline \
  && python3 setup.py install \
  && cd .. \
  && rm -R ./np_inline
# Copy the source files for the app
ADD src /mediakraken

EXPOSE 8903

CMD ["/bin/ash"]
