docker tag alpine_appserver:latest th-dockerhub-1:5000/mediakraken/mkserver:latest
docker tag alpine_broadcast:latest th-dockerhub-1:5000/mediakraken/mkbroadcast:latest
docker tag alpine_database:latest th-dockerhub-1:5000/mediakraken/mkdatabase:latest
docker tag alpine_download:latest th-dockerhub-1:5000/mediakraken/mkdownload:latest
docker tag alpine_ffprobe th-dockerhub-1:5000/mediakraken/mkffprobe:latest
docker tag alpine_hardware th-dockerhub-1:5000/mediakraken/mkhardware:latest
docker tag alpine_metadata:latest th-dockerhub-1:5000/mediakraken/mkmetadata:latest
docker tag alpine_nginx:latest th-dockerhub-1:5000/mediakraken/mknginx:latest
docker tag alpine_pgbounce:latest th-dockerhub-1:5000/mediakraken/mkpgbounce:latest
docker tag alpine_rabbit:latest th-dockerhub-1:5000/mediakraken/mkrabbitmq:latest
docker tag alpine_redis:latest th-dockerhub-1:5000/mediakraken/mkredis:latest
docker tag alpine_rokuthumb:latest th-dockerhub-1:5000/mediakraken/mkrokuthumb:latest
docker tag alpine_webserver:latest th-dockerhub-1:5000/mediakraken/mkwebapp:latest
