[package]
name = "mk_lib_database"
version = "0.0.1"
edition = "2018"

[dependencies]
tokio = { version = "1.6.0", features = ["full"] }
tokio-postgres = { version = "0.7.2", features = ["with-serde_json-1"] }