# Download base image
FROM alpine:3.5

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image holds the broadcast server"

# create work dir
RUN mkdir /mediakraken

# copy PIP requirements
ADD requirements.txt /mediakraken

WORKDIR /mediakraken

RUN apk add --update \
  python \
  py-pip \
  && pip install -r requirements.txt \
  && rm -rf /var/cache/apk/*

# Copy the source files for the app
ADD src /mediakraken

EXPOSE 9101

CMD ["/bin/ash"]
