# Download base image
FROM mediakraken/mkbase37

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image holds the broadcast server"

# copy PIP requirements
ADD requirements.txt /mediakraken

WORKDIR /mediakraken

RUN pip install -r requirements.txt \
  && apk del py-pip \
  && rm -rf /var/cache/apk/*

# Copy the source files for the app
ADD src /mediakraken

EXPOSE 9101

CMD ["/bin/ash"]
