# Download base image
FROM mediakraken/mkbaseffmpeg:dev-0.1.12

MAINTAINER Quinn D Granfor, spootdev@gmail.com

LABEL www.mediakraken.org.version="dev-0.1.12"
LABEL www.mediakraken.org.release-date="2016-10-28"
LABEL Description="This image holds the main slave app"

# don't create /mediakraken as it's in the base image

# copy PIP requirements
ADD requirements.txt /mediakraken
WORKDIR /mediakraken

RUN apk add --update \
  py-pip\
  && pip install -r requirements.txt \
  apk del \
  py-pip
