# Download base image
FROM mediakraken/mkbaseffmpeg:dev-0.1.12

MAINTAINER Quinn D Granfor, spootdev@gmail.com

LABEL www.mediakraken.org.version="dev-0.1.12"
LABEL www.mediakraken.org.release-date="2016-10-28"
LABEL Description="This image holds the main slave app"

# don't create /mediakraken as it's in the base image

# Copy the source files for the app
ADD src /mediakraken

# copy PIP requirements
ADD requirements.txt /mediakraken
WORKDIR /mediakraken

ENTRYPOINT ["python", "/mediakraken/main_server_slave.py"]
