# Download base image
FROM alpine:3.6

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image hosts the postgresql database"

ENV PG_MAJOR 9.6
ENV PG_VERSION 9.6.6

ENV PATH /usr/lib/postgresql/$PG_MAJOR/bin:$PATH
ENV PGDATA /var/lib/postgresql/data

ENV LANG en_US.utf8

RUN apk update && apk add build-base readline-dev zlib-dev libxml2-dev glib-lang wget gnupg ca-certificates bison flex perl && \
    mkdir -p /docker-entrypoint-initdb.d && \
    wget https://ftp.postgresql.org/pub/source/v$PG_VERSION/postgresql-$PG_VERSION.tar.bz2 -O /tmp/postgresql-$PG_VERSION.tar.bz2 && \
    tar xvfj /tmp/postgresql-$PG_VERSION.tar.bz2 -C /tmp && \
    cd /tmp/postgresql-$PG_VERSION && ./configure --enable-integer-datetimes --enable-thread-safety --prefix=/usr/local --with-libedit-preferred && make world && make install world && make -C contrib install && \
    cd /tmp/postgresql-$PG_VERSION/contrib && make && make install && \
    apk --purge del build-base zlib-dev libxml2-dev wget gnupg ca-certificates perl && \
    rm -r /tmp/postgresql-$PG_VERSION* /var/cache/apk/*

VOLUME /var/lib/postgresql/data:/var/lib/postgresql/data

COPY docker-entrypoint-initdb.d /docker-entrypoint-initdb.d

COPY docker-entrypoint.sh /

COPY db_trgm.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 5432
CMD ["postgres"]
