# Download base image
FROM mediakraken/mkbase37py3

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image downloads and maintains all metadata"

# copy PIP requirements
ADD requirements.txt /mediakraken
WORKDIR /mediakraken

# Update repository and install packages
RUN apk add --update \
  ca-certificates \
  cifs-utils \
  nfs-utils \
  postgresql-client \
  gcc \
  linux-headers \
  musl-dev \
  postgresql-dev \
  python3-dev \
  libffi-dev \
  python \
  openrc \
  && pip3 install pytest-runner \
  && pip3 install -r requirements.txt \
  && pip3 uninstall -y pytest_runner \
  && apk del gcc linux-headers musl-dev postgresql-dev python3-dev \
  && rm requirements.txt \
  && apk add \
  py-setuptools \
  && rm -rf /var/cache/apk/* \
  && rc-update add netmount \
  && rc-update add rpcbind
#  && pip3 install -e git+https://github.com/agonzalezro/python-opensubtitles#egg=python-opensubtitles #TODO removed for now

RUN mkdir /mediakraken/cache
ADD wait-for-it-ash.sh /mediakraken
# Copy the source files for the app
ADD src /mediakraken

CMD ["/bin/ash"]
