[package]
name = "myapp"
version = "0.0.1"
edition = "2018"

[profile.release]
panic = 'abort'

[dependencies]
amiquip = { version = "0.4", default-features = false }
tokio = { version = "1.6.0", features = ["full"] }

[dev-dependencies]
tokio-test = "*"