language: shell
os: linux
dist: bionic

services:
  - docker

env:
  - WINE_BRANCH=devel NO_RDP=no
  - WINE_BRANCH=devel NO_RDP=yes
  - WINE_BRANCH=stable NO_RDP=no
  - WINE_BRANCH=stable NO_RDP=yes

script:
  - bash build

deploy:
  provider: script
  script: bash deploy
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE = cron
