# Download base image
FROM alpine:3.6

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image holds the beets app"

# create work dir
RUN mkdir /mediakraken

# copy PIP requirements
ADD requirements.txt /mediakraken
WORKDIR /mediakraken

RUN apk add --update \
  python \
  py-pip \
  && pip install --upgrade pip \
  && pip install -r requirements.txt \
  && apk del \
  py-pip \
  && rm -rf /var/cache/apk/* \
  && rm requirements.txt

ADD wait-for-it-ash.sh /mediakraken

CMD ["/bin/ash"]
