# Download base image
FROM mediakraken/mkwebbase:dev-0.1.12

MAINTAINER Quinn D Granfor, spootdev@gmail.com

LABEL www.mediakraken.org.version="dev-0.1.12"
LABEL www.mediakraken.org.release-date="2016-10-28"
LABEL Description="This image hosts web/flask API"

