docker push mediakraken/mkslave:latest
docker push mediakraken/mkserver:latest
docker push mediakraken/mkdatabase:latest
docker push mediakraken/mkdevicescan:latest
docker push mediakraken/mkmetadata:latest
docker push mediakraken/mknginx:latest
docker push mediakraken/mkopenldap:latest
docker push mediakraken/mkpgbounce:latest
docker push mediakraken/mkredis:latest
docker push mediakraken/mkwebapp:latest
