docker push mediakraken/mkmusicbrainz:latest
docker push mediakraken/mkbroadcast:latest
docker push mediakraken/mkdatabase:latest
docker push mediakraken/mkdevicescan:latest
docker push mediakraken/mkbaseffmpeg:latest
docker push mediakraken/mkbaseffmpegnvidia:latest
docker push mediakraken/mkbaseffmpegnvidiadebian:latest
docker push mediakraken/mkbasenvidiadebain:latest
docker push mediakraken/mkslave:latest
docker push mediakraken/mkslavenvidia:latest
docker push mediakraken/mkslavenvidiadebian:latest
docker push mediakraken/mkserver:latest
docker push mediakraken/mkmetadata:latest
docker push mediakraken/mknginx:latest
docker push mediakraken/mkopenldap:latest
docker push mediakraken/mkpgbounce:latest
docker push mediakraken/mkrabbitmq:latest
docker push mediakraken/mkredis:latest
docker push mediakraken/mkwebapp:latest
docker push mediakraken/mktransmission:latest
docker push mediakraken/mkmumble:latest
docker push mediakraken/mkphppgadmin:latest
