docker tag mk_appserver:latest mediakraken/mkserver:latest
docker tag mk_brainz:latest mediakraken/mkbrainz:latest
docker tag mk_broadcast:latest mediakraken/mkbroadcast:latest
docker tag mk_database:latest mediakraken/mkdatabase:latest
docker tag mk_devicescan:latest mediakraken/mkdevicescan:latest
docker tag mk_metadata:latest mediakraken/mkmetadata:latest
docker tag mk_nginx:latest mediakraken/mknginx:latest
docker tag mk_openldap:latest mediakraken/mkopenldap:latest
docker tag mk_pgbounce:latest mediakraken/mkpgbounce:latest
docker tag mk_rabbit:latest mediakraken/mkrabbitmq:latest
docker tag mk_redis:latest mediakraken/mkredis:latest
docker tag mk_webserver:latest mediakraken/mkwebapp:latest
