docker tag mk_appserver:latest mediakraken/mkserver:latest
docker tag mk_broadcast:latest mediakraken/mkbroadcast:latest
docker tag mk_database:latest mediakraken/mkdatabase:latest
docker tag mk_devicescan:latest mediakraken/mkdevicescan:latest
docker tag mk_metadata:latest mediakraken/mkmetadata:latest
docker tag mk_nginx:latest mediakraken/mknginx:latest
docker tag mk_pgbounce:latest mediakraken/mkpgbounce:latest
docker tag mk_rabbit:latest mediakraken/mkrabbitmq:latest
docker tag mk_redis:latest mediakraken/mkredis:latest
docker tag mk_webserver:latest mediakraken/mkwebapp:latest
docker tag mk_transmission:latest mediakraken/mktransmission:latest
docker tag mk_musicbrainz mediakraken/mkmusicbrainz:latest
docker tag mk_mumble mediakraken/mkmumble:latest
docker tag mk_phppgadmin mediakraken/mkphppgadmin:latest
docker tag mk_smtp mediakraken/mksmtp:latest
