# Download base image
FROM mediakraken/mkbase37

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image holds the image for the web server app"

# copy PIP requirements
ADD requirements.txt /mediakraken
WORKDIR /mediakraken

# Update repository and install packages
RUN apk add --update \
  postgresql-client \
  ack \
  curl-dev \
  git \
  gcc \
  jpeg-dev \
  libxml2-dev \
  libxslt-dev \
  linux-headers \
  musl-dev \  
  nginx \
  openrc \
  py-cffi \
  py-redis \
  python-dev \
  postgresql-dev \
  cifs-utils \
  nfs-utils \
  ca-certificates \
  openssl \
  py2-numpy \
  && export PYCURL_SSL_LIBRARY=openssl \
  && pip install pycurl \
  && pip install -r requirements.txt \
  && pip install -e git+https://github.com/LevPasha/Instagram-API-python.git#egg=InstagramAPI \
  && apk del \
  gcc \
  git \
  musl-dev \
  linux-headers \
  py-pip \
  python-dev \
  postgresql-dev \
  && rm requirements.txt \
  && apk add \
  uwsgi-python \
  uwsgi-router_uwsgi \
  py-setuptools \
  && cp /usr/lib/uwsgi/python_plugin.so /mediakraken/. \
  && rm -rf /var/cache/apk/* \
  && rc-update add netmount \
  && rc-update add rpcbind

COPY nginx.conf /etc/nginx/nginx.conf
ADD wait-for-it-ash.sh /mediakraken
# Copy the source files for the app
ADD src /mediakraken

EXPOSE 8080
CMD ["/bin/ash"]
