# Download base image
FROM alpine:3.4

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image holds the image for the web server app"

RUN mkdir /mediakraken
# copy PIP requirements
ADD requirements.txt /mediakraken
WORKDIR /mediakraken

# Update repository and install packages
RUN apk add --update \
  postgresql-client \
  ack \
  curl-dev \
  git \
  gcc \
  jpeg-dev \
  libxml2-dev \
  libxslt-dev \
  linux-headers \
  musl-dev \  
  openrc \
  py-cffi \
  py-pip \
  py-redis \
  python-dev \
  postgresql-dev \
  cifs-utils \
  nfs-utils \
  ca-certificates \
  openssl \
  nginx \
  && pip install --upgrade pip \
  && pip install -r requirements.txt \
  && pip install -e git+https://github.com/LevPasha/Instagram-API-python.git#egg=InstagramAPI \
  && apk del \
  gcc \
  git \
  musl-dev \
  linux-headers \
  py-pip \
  python-dev \
  postgresql-dev \
  && rm requirements.txt \
  && apk add \
  uwsgi-python \
  uwsgi-router_uwsgi \
  py-setuptools \
  && cp /usr/lib/uwsgi/python_plugin.so /mediakraken/. \
  && rm -rf /var/cache/apk/* \
  && rc-update add netmount \
  && rc-update add rpcbind

ADD wait-for-it-ash.sh /mediakraken
# Copy the source files for the app
ADD src /mediakraken
ADD ip2country /mediakraken/ip2country
RUN cd ip2country \
  && python setup.py install \
  && cd .. \
  && rm -R ./ip2country
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080
CMD ["/bin/ash"]
