#!/usr/bin/expect

set timeout -1
spawn "/srv/assets/bf1942_lnxded-1.6-rc2.run" --keep --target ../bf1942

expect {
       eof { send_user "\nunexpected eof in extraction\n"; exit 1 }
       "*ress return"
}
       
send "^c"

send_user "\nfinished\n"