# Download base image
FROM mediakraken/mkbaseffmpeg

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image holds the ripper app"

# create work dir
RUN mkdir /mediakraken

# copy PIP requirements
ADD requirements.txt /mediakraken
WORKDIR /mediakraken

RUN apk add --update \
  abcde \
  openjdk8-jre-base \
  python \
  py-pip \
  && pip install --upgrade pip \
  && pip install -r requirements.txt \
  && apk del \
  py-pip \
  && rm -rf /var/cache/apk/* \
  && rm requirements.txt

# Copy the source files for the app
ADD src /mediakraken

CMD ["/bin/ash"]
