# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mk_browse_movie.ui'
#
# Created: Tue Aug  8 20:33:34 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MK_Browse_Movie(object):
    def setupUi(self, MK_Browse_Movie):
        MK_Browse_Movie.setObjectName("MK_Browse_Movie")
        MK_Browse_Movie.resize(765, 612)
        self.centralWidget = QtWidgets.QWidget(MK_Browse_Movie)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.browse_movie_frame_right = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.browse_movie_frame_right.sizePolicy().hasHeightForWidth())
        self.browse_movie_frame_right.setSizePolicy(sizePolicy)
        self.browse_movie_frame_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.browse_movie_frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.browse_movie_frame_right.setObjectName("browse_movie_frame_right")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.browse_movie_frame_right)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_button_images = QtWidgets.QPushButton(self.browse_movie_frame_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_button_images.sizePolicy().hasHeightForWidth())
        self.main_button_images.setSizePolicy(sizePolicy)
        self.main_button_images.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/photo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_button_images.setIcon(icon)
        self.main_button_images.setObjectName("main_button_images")
        self.verticalLayout_2.addWidget(self.main_button_images)
        self.main_button_radio = QtWidgets.QPushButton(self.browse_movie_frame_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_button_radio.sizePolicy().hasHeightForWidth())
        self.main_button_radio.setSizePolicy(sizePolicy)
        self.main_button_radio.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/radio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_button_radio.setIcon(icon1)
        self.main_button_radio.setObjectName("main_button_radio")
        self.verticalLayout_2.addWidget(self.main_button_radio)
        self.main_button_books = QtWidgets.QPushButton(self.browse_movie_frame_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_button_books.sizePolicy().hasHeightForWidth())
        self.main_button_books.setSizePolicy(sizePolicy)
        self.main_button_books.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/books.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_button_books.setIcon(icon2)
        self.main_button_books.setObjectName("main_button_books")
        self.verticalLayout_2.addWidget(self.main_button_books)
        self.main_button_settings = QtWidgets.QPushButton(self.browse_movie_frame_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_button_settings.sizePolicy().hasHeightForWidth())
        self.main_button_settings.setSizePolicy(sizePolicy)
        self.main_button_settings.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_button_settings.setIcon(icon3)
        self.main_button_settings.setObjectName("main_button_settings")
        self.verticalLayout_2.addWidget(self.main_button_settings)
        self.gridLayout.addWidget(self.browse_movie_frame_right, 0, 2, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 2)
        self.browse_movie_vert_scroll = QtWidgets.QScrollBar(self.centralWidget)
        self.browse_movie_vert_scroll.setOrientation(QtCore.Qt.Vertical)
        self.browse_movie_vert_scroll.setObjectName("browse_movie_vert_scroll")
        self.gridLayout.addWidget(self.browse_movie_vert_scroll, 0, 3, 1, 1)
        self.browse_movie_frame_bottom = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.browse_movie_frame_bottom.sizePolicy().hasHeightForWidth())
        self.browse_movie_frame_bottom.setSizePolicy(sizePolicy)
        self.browse_movie_frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.browse_movie_frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.browse_movie_frame_bottom.setObjectName("browse_movie_frame_bottom")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.browse_movie_frame_bottom)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.browse_movie_genre = QtWidgets.QComboBox(self.browse_movie_frame_bottom)
        self.browse_movie_genre.setObjectName("browse_movie_genre")
        self.horizontalLayout.addWidget(self.browse_movie_genre)
        self.browse_movie_rating = QtWidgets.QComboBox(self.browse_movie_frame_bottom)
        self.browse_movie_rating.setObjectName("browse_movie_rating")
        self.horizontalLayout.addWidget(self.browse_movie_rating)
        self.gridLayout.addWidget(self.browse_movie_frame_bottom, 1, 0, 1, 4)
        MK_Browse_Movie.setCentralWidget(self.centralWidget)

        self.retranslateUi(MK_Browse_Movie)
        QtCore.QMetaObject.connectSlotsByName(MK_Browse_Movie)

    def retranslateUi(self, MK_Browse_Movie):
        _translate = QtCore.QCoreApplication.translate
        MK_Browse_Movie.setWindowTitle(_translate("MK_Browse_Movie", "MediaKraken"))

