version: '3'

services:
  webserver:
    build:
      context: ./thebuggenie-docker
      dockerfile: Dockerfile
    container_name: mkbuggenie
    ports:
      - "8080:80"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - buggenie_network
    restart: unless-stopped

  # runs the nginx proxy service
  nginx:
    build:
      context: ./thebuggenie-nginx
      dockerfile: dockerfile-nginx
    container_name: mkbugnginx
    entrypoint: /usr/bin/wait-for-it-ash.sh -h webserver -p 8080 -t 30 -- nginx
    volumes:
      - /var/log/mediakraken/nginx:/var/log/mediakraken/nginx
      - /var/opt/mediakraken/certs:/etc/nginx/certs
    ports:
      - "443:443"
    networks:
      - buggenie_network
    restart: unless-stopped

# Docker private networks
networks:
  buggenie_network:
    driver: bridge
