apiVersion: v1
kind: PersistentVolume
metadata:
  name: mk-nfs-pv
spec:
  capacity:
    storage: 250Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /home/k8s
    server: th-mkk8snfs-1