apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default

spec:
  volumes:
    - name: postgres-pv-storage
      persistentVolumeClaim:
        claimName: mk-nfs-pvc
  replicas: 1
  image: mediakraken/mkdatabase:${BRANCH}

  env:
     - name: POSTGRES_PASSWORD
       valueFrom:
          secretKeyRef:
             name: mypostgres-secret
             key: superUserPassword

     - name: POSTGRES_REPLICATION_PASSWORD
       valueFrom:
          secretKeyRef:
             name: mypostgres-secret
             key: replicationUserPassword