version: '2'

ENV MKVERSION="dev-0.1.12"

services:
  app:
    image: mediakraken/mkserver:$MKVERSION
    ports:
      - "8900:8080"
    networks:
      - mknetwork

  database:
    image: mediakraken/mkdatabase::$MKVERSION
    environment: POSTGRES_PASSWORD: jf2049jf42j
    networks:
      - mknetwork

volumes:
  redis-data:
    driver: local

networks:
  mknetwork:
    driver: overlay

