version: '2'
# MediaKraken

services:
  # Main app server which controls the show and transcodes
  appserver:
    build:
      context: ./ComposeMediaKrakenServer
      dockerfile: dockerfile-appserver
    environment:
      - POSTGRES_PASSWORD=${DBPASS}
    container_name: mkserver
    depends_on:
      - database
    entrypoint: ./wait-for-it.sh -h database -p 5432 -t 30
    ports:
      - "8903:5000"
    volumes:
      - /mediakraken/log:/var/log/mediakraken
    networks:
      - mediakraken-network
      - mediakraken-dbnetwork

  # slave app server which transcodes
#  appslave:
#    build:
#      context: ./ComposeMediaKrakenSlave
#      dockerfile: dockerfile-appslave
#    environment:
#      - POSTGRES_PASSWORD=${DBPASS}
#    container_name: mkslave
#    depends_on:
#      - database
#    entrypoint: ./wait-for-it.sh -h database -p 5432 -t 30
#    volumes:
#      - ./log:/var/log/mediakraken
#    networks:
#      - mediakraken-network

  # Postgresql server
  database:
    build:
      context: ./ComposeMediaKrakenDatabase
      dockerfile: dockerfile-database
    environment:
      - POSTGRES_DB=metamandb
      - POSTGRES_USER=metamanpg
      - POSTGRES_PASSWORD=${DBPASS}
    container_name: mkdatabase
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    networks:
      - mediakraken-dbnetwork

  # Runs the webapi for 3rd party clients
#  webapi:
#    build:
#      context: ./ComposeMediaKrakenWebAPI
#      dockerfile: dockerfile-webapi
#    environment:
#      - POSTGRES_PASSWORD=${DBPASS}
#    container_name: mkwebapi
#    depends_on:
#      - database
#    entrypoint: ./wait-for-it.sh -h database -p 5432 -t 30
#    ports:
#      - "8901:8080"
#    volumes:
#      - /mediakraken/log:/var/log/mediakraken
#    networks:
#      - mediakraken-dbnetwork

  # Runs the web service for the main server application
  webserver:
    build:
      context: ./ComposeMediaKrakenWebServer
      dockerfile: dockerfile-webserver
    environment:
      - POSTGRES_PASSWORD=${DBPASS}
    container_name: mkwebapp
    depends_on:
      - database
    entrypoint: ./wait-for-it.sh -h database -p 5432 -t 30
    ports:
      - "8900:8080"
    volumes:
      - /mediakraken/log:/var/log/mediakraken
    networks:
      - mediakraken-dbnetwork

# Docker private networks
networks:
  # Twisted communications network
  mediakraken-network:
    driver: bridge
  # Database communications network
  mediakraken-dbnetwork:
    driver: bridge
