version: '2'

services:
  app:
    image: mediakraken/mkserver:dev-0.1.12
    ports:
      - "8900:8080"
    networks:
      - mknetwork

  database:
    image: mediakraken/mkdatabase:dev-0.1.12
    environment: POSTGRES_PASSWORD: jf2049jf42j
    networks:
      - mknetwork

volumes:
  redis-data:
    driver: local

networks:
  mknetwork:
    driver: overlay

