"""
  Copyright (C) 2021 Quinn D Granfor <spootdev@gmail.com>

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  version 2, as published by the Free Software Foundation.

  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License version 2 for more details.

  You should have received a copy of the GNU General Public License
  version 2 along with this program; if not, write to the Free
  Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
  MA 02110-1301, USA.
"""

import asyncio
import sys

from common import common_config_ini
from common import common_logging_elasticsearch_httpx
from common import common_system

'''
# Mister file locations
/media/fat          	Micro SD card
/media/fat/_Arcade  	Upload Arcade cores here
/media/fat/_Computer	Upload Computer cores here
/media/fat/_Console 	Upload Console cores here
/media/fat/config   	Per core configs. Generated by each core as you use them
/media/fat/games    	Upload games/ROMs/images here
/media/fat/MiSTer.ini	MiSTer global config e.g. to change video mode / overscan
'''

'''
for chd in *.chd; do chdman extractcd -i "$chd" -o "${chd%.chd}.cue"; done
'''

source_directory = ''
target_directory = ''

async def main(loop):
    # start logging
    await common_logging_elasticsearch_httpx.com_es_httpx_post_async(message_type='info',
                                                                     message_text='START',
                                                                     index_name='async_mister_converter')

    # open the database
    option_config_json, db_connection = \
        await common_config_ini.com_config_read_async(loop=loop,
                                                      as_pool=False)

    # commit all changes
    await db_connection.db_commit(db_connection=None)

    # close DB
    await db_connection.db_close(db_connection=None)

    await common_logging_elasticsearch_httpx.com_es_httpx_post_async(message_type='info',
                                                                     message_text='STOP')


if __name__ == "__main__":
    # verify this program isn't already running!
    if common_system.com_process_list(
            process_name='/usr/bin/python3 /mediakraken/async_mister_converter.py'):
        sys.exit(0)
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(loop))
    loop.close()
