version: '2'
# MediaKraken

# Volumes are HOST directory and then CONTAINER directory

services:
  # Main app server which controls the show and transcodes
  appserver:
    image: mediakraken/mkserver:latest
    environment:
      - POSTGRES_DB=${DBDATABASE}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
    container_name: mkserver
    depends_on:
      - pgbounce
    entrypoint: ./wait-for-it-ash.sh -h pgbounce -p 6432 -t 30 -- python main_server.py
    ports:
      - "8903:8903"
    volumes:
      - /var/log/mediakraken:/mediakraken/log
      - /var/opt/mediakraken/devices:/mediakraken/devices
      - /home/mediakraken:/mediakraken/mnt
    networks:
      - mediakraken-network
      - mediakraken-dbnetwork
    restart: unless-stopped
    # to allow mount nfs/cifs
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH

  # slave app server which transcodes
  appslave:
    image: mediakraken/mkslave:latest
    environment:
      - POSTGRES_DB=${DBDATABASE}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
    container_name: mkslave
    depends_on:
      - appserver
      - pgbounce
    entrypoint: ./wait-for-it-ash.sh -h appserver -p 8903 -t 30 -- python main_server_slave.py
    volumes:
      - /var/log/mediakraken:/mediakraken/log
      - /home/mediakraken:/mediakraken/mnt
    networks:
      - mediakraken-network
      - mediakraken-dbnetwork
    restart: unless-stopped
    # to allow mount nfs/cifs
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH

  # Postgresql server
  database:
    image: mediakraken/mkdatabase:latest
    environment:
      - POSTGRES_DB=${DBDATABASE}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
    container_name: mkdatabase
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    networks:
      - mediakraken-dbnetwork
    restart: unless-stopped

  # pgbouncer
  pgbounce:
    image: mediakraken/mkpgbounce:latest
    environment:
      - DB_HOST=${DBHOST}
      - DB_USER=${DBUSER}
      - DB_PASSWORD=${DBPASS}
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=500
      - DEFAULT_POOL_SIZE=85
      - SERVER_RESET_QUERY=DISCARD ALL
    container_name: mkpgbounce
    depends_on:
      - database
    entrypoint: ./wait-for-it-ash.sh -h database -p 5432 -t 30 -- ./entrypoint.sh
    networks:
      - mediakraken-dbnetwork
    restart: unless-stopped

  # scan for new hardware devices
  devicescan:
    image: mediakraken/mkdevicescan:latest
    container_name: mkdevicescan
    entrypoint: python main_hardware_discover.py
    volumes:
      - /var/log/mediakraken:/mediakraken/log
      - /var/opt/mediakraken/devices:/mediakraken/devices
    network_mode: host
    restart: never

  # runs the server to fetch/process all metadata
  metadata:
    image: mediakraken/mkmetadata:latest
    environment:
      - POSTGRES_DB=${DBDATABASE}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
    container_name: mkmetadata
    depends_on:
      - pgbounce
    entrypoint: ./wait-for-it-ash.sh -h pgbounce -p 6432 -t 30 -- python main_server_metadata_api.py
    volumes:
      - /var/log/mediakraken:/mediakraken/log
      - /home/mediakraken:/mediakraken/mnt
      - /var/opt/mediakraken/images:/mediakraken/web_app/MediaKraken/static/meta/images
    networks:
      - mediakraken-dbnetwork
    restart: unless-stopped
    # to allow mount nfs/cifs
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH

  # musicbrainz replicator
#  brainz:
#    image: mediakraken/mkbrainz:latest
#    environment:
#      - BRAINZCODE=${BRAINZCODE}
#    container_name: mkbrainz
#    networks:
#      - mediakraken-network
#    restart: unless-stopped

  # runs the nginx proxy service
  nginx:
    image: mediakraken/mknginx:latest
    container_name: mknginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mediakraken-network
    restart: unless-stopped

  # runs the openldap
#  openldap:
#    image: mediakraken/mkopenldap:latest
#    container_name: mkopenldap
#    ports:
#      - "389:389"
#      - "636:636"
#    networks:
#      - mediakraken-network
#    restart: unless-stopped

  # runs the redis service for flask
  redis:
    image: mediakraken/mkredis:latest
    container_name: mkredis
    ports:
      - "6379:6379"
    networks:
      - mediakraken-network
    restart: unless-stopped

  # Runs the web service for the main server application
  webserver:
    image: mediakraken/mkwebapp:latest
    environment:
      - POSTGRES_DB=${DBDATABASE}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
    container_name: mkwebapp
    depends_on:
      - pgbounce
      - redis
      - nginx
    entrypoint: ./wait-for-it-ash.sh -h pgbounce -p 6432 -t 30 -- uwsgi --socket 0.0.0.0:8080 --protocol http --chdir=./web_app --ini ./web_app/mediakraken_uwsgi_alpine.ini
    ports:
      - "8900:8080"
    volumes:
      - /var/log/mediakraken:/mediakraken/log
      - /home/mediakraken:/mediakraken/mnt
      - /var/opt/mediakraken/images:/mediakraken/web_app/MediaKraken/static/meta/images
    networks:
      - mediakraken-network
      - mediakraken-dbnetwork
    restart: unless-stopped
    # to allow mount nfs/cifs
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH

# Docker private networks
networks:
  # Twisted communications network
  mediakraken-network:
    driver: bridge
  # Database communications network
  mediakraken-dbnetwork:
    driver: bridge

