# Download base image
FROM mediakraken/mkbase38py3:dev

LABEL AUTHOR="Quinn D Granfor, spootdev@gmail.com"
LABEL Description="This image holds the castpy app"

WORKDIR /mediakraken

# Copy the source files for the app
COPY src /mediakraken

CMD ["/bin/ash"]
